prefix skos: <http://www.w3.org/2004/02/skos/core#> 
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
prefix org: <http://www.w3.org/ns/org#> 
prefix vcard: <http://www.w3.org/2006/vcard/ns#> 
prefix foaf:  <http://xmlns.com/foaf/0.1/>


//// Visualizza Tutti i risultati


SELECT ?nome_associazione ?link ?stato ?regione ?cap ?locality ?indirizzo (GROUP_CONCAT(DISTINCT ?email ; separator= " ; ") AS ?c_email)
(GROUP_CONCAT(DISTINCT ?numero ; separator= " ; ") AS ?c_numeri)
(GROUP_CONCAT(DISTINCT ?purp_label ; separator= ' ; ') AS ?c_purpose) WHERE{
?org a org:Organization;
skos:prefLabel ?nome_associazione;
org:purpose ?purpose.
?purpose rdfs:label ?purp_label.
OPTIONAL{ ?org foaf:homepage ?link}
OPTIONAL{ ?org org:hasSite ?site.
          ?site a org:Site;
          org:siteAddress ?site_address.

          ?site_address a vcard:Location.
          OPTIONAL {?site_address vcard:hasAddress ?address.
                    ?address a vcard:Work.
                    OPTIONAL {?address vcard:country-name ?stato;
                               vcard:region ?regione;
                               vcard:postal-code ?cap;
                               vcard:locality ?locality;
                               vcard:street-address ?indirizzo;
                              }

                    OPTIONAL {?site_address vcard:hasEmail ?email
                              

                             }
                    OPTIONAL {?site_address vcard:hasTelephone ?telephone.
                              ?telephone a vcard:Voice;
                              vcard:hasValue ?numero

                             }
          }

}
}

GROUP BY ?nome_associazione ?link ?stato ?regione ?cap ?locality ?indirizzo 


//// Visualizza solo le associazioni con un sito web


SELECT ?nome_associazione ?link ?stato ?regione ?cap ?locality ?indirizzo (GROUP_CONCAT(DISTINCT ?email ; separator= " ; ") AS ?c_email)
(GROUP_CONCAT(DISTINCT ?numero ; separator= " ; ") AS ?c_numeri)
(GROUP_CONCAT(DISTINCT ?purp_label ; separator= ' ; ') AS ?c_purpose) WHERE{
?org a org:Organization;
skos:prefLabel ?nome_associazione;
foaf:homepage ?link;
org:purpose ?purpose.
?purpose rdfs:label ?purp_label.

OPTIONAL{ ?org org:hasSite ?site.
          ?site a org:Site;
          org:siteAddress ?site_address.

          ?site_address a vcard:Location.
          OPTIONAL {?site_address vcard:hasAddress ?address.
                    ?address a vcard:Work.
                    OPTIONAL {?address vcard:country-name ?stato;
                               vcard:region ?regione;
                               vcard:postal-code ?cap;
                               vcard:locality ?locality;
                               vcard:street-address ?indirizzo;
                              }

                    OPTIONAL {?site_address vcard:hasEmail ?email
                              

                             }
                    OPTIONAL {?site_address vcard:hasTelephone ?telephone.
                              ?telephone a vcard:Voice;
                              vcard:hasValue ?numero

                             }
          }

}
}

GROUP BY ?nome_associazione ?link ?stato ?regione ?cap ?locality ?indirizzo 


//// Visualizza solo le associazioni che hanno informazioni sulla sede